language: csharp
sudo: required
dist: trusty
dotnet: 1.0.1
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
env:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script: 
    - chmod +x build.sh
    - ./build.sh
